name: windows

on:
  push:
    branches: [ "master", "current", "release/*" ]
  pull_request:
    branches: [ "master", "current", "release/*" ]

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
         shell: msys2 {0}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msys2-root: ${{ runner.workspace }}/msys2
        update: true

    - name: Install required packages
      shell: msys2 {0}
      run: |
        pacman -Syu --noconfirm mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-qt6-base mingw-w64-ucrt-x86_64-qt6-tools mingw-w64-ucrt-x86_64-qt6-svg mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-python bison flex dos2unix mingw-w64-ucrt-x86_64-gperf -v

        
    - name: Build CMake project
      if: ${{ env.ENABLE_BUILD == 'true' }}
      run: |
        cmake -B ${{github.workspace}}/build -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build -j`nproc` --config ${{env.BUILD_TYPE}}
      

 
