name: windows

on:
  push:
    branches: [ "develop", "release/*" ]
  pull_request:
    branches: [ "develop", "release/*" ]

env:
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
         shell: msys2 {0}
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msys2-root: ${{ runner.workspace }}/msys2
        msystem: UCRT64
        cache: true
        update: true
        install: >-
          git
          mingw-w64-ucrt-x86_64-cmake 
          mingw-w64-ucrt-x86_64-gcc 
          mingw-w64-ucrt-x86_64-qt6-base 
          mingw-w64-ucrt-x86_64-qt6-tools 
          mingw-w64-ucrt-x86_64-qt6-svg 
          mingw-w64-ucrt-x86_64-make 
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-python 
          bison 
          flex 
          dos2unix 
          mingw-w64-ucrt-x86_64-gperf
          
    - name: Build with cmake
      run: |
        ls -la
        cmake.exe -B build/ -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake.exe --build build/ -j`nproc` --config ${{env.BUILD_TYPE}}
        
      

 
